export default {
  hotel: 'Hoteles',
  lounge: 'Salones',
  space: 'Espacios de hotel',
  promotion: 'Promociones',
  mediafile: 'Archivos multimedia',
  textfile: 'Archivos de texto',
  extra: 'Extras',
  montage: 'Disposiciones',
  service: 'Servicios',
  brand: 'Marcas',
  section: 'Páginas',
  language: 'Idiomas',
  country: 'Paises',
  city: 'Ciudades',
  type: 'Tipos de hotel',
  eventtype: 'Tipos de evento',
  user: 'Usuarios',
  story: 'Casos de éxito',
  mailsent: 'Emails enviados'
}
